#!/bin/bash

# Path to your README.md file
README_FILE="README.md"
TEMP_FILE=$(mktemp)

# Get the latest commit message
COMMIT_MSG=$(git log -1 --pretty=%B)
COMMIT_DATE=$(git log -1 --pretty=%ad --date=short)
COMMIT_HASH=$(git log -1 --pretty=%h)

# Find the Changelog section in README.md
CHANGELOG_START=$(grep -n "^## Changelog" "$README_FILE" | cut -d: -f1)

if [ -z "$CHANGELOG_START" ]; then
    # If no Changelog section exists, create it before ## Support
    SUPPORT_LINE=$(grep -n "^## Support" "$README_FILE" | cut -d: -f1)
    
    # Add Changelog section before Support
    sed "${SUPPORT_LINE}i\\\n## Changelog\n\n### Unreleased\n" "$README_FILE" > "$TEMP_FILE"
    mv "$TEMP_FILE" "$README_FILE"
    
    # Get the new Changelog position
    CHANGELOG_START=$(grep -n "^## Changelog" "$README_FILE" | cut -d: -f1)
fi

# Add the new commit under Unreleased
NEXT_LINE=$((CHANGELOG_START + 3))
sed "${NEXT_LINE}i\- ${COMMIT_DATE} [\`${COMMIT_HASH}\`](../../commit/${COMMIT_HASH}): ${COMMIT_MSG}" "$README_FILE" > "$TEMP_FILE"

# Move the temporary file back
mv "$TEMP_FILE" "$README_FILE"

# Stage the README.md changes
git add "$README_FILE"

# Amend the commit to include the README changes
git commit --amend --no-edit 